repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.23.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
- repo: https://github.com/golangci/golangci-lint
  rev: v1.64.8
  hooks:
  - id: golangci-lint
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-mod-tidy
